name: Build Python wheels and publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_linux:
    name: Linux Wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install cibuildwheel
      run: python3 -m pip install cibuildwheel==3.4.1

    - name: Build wheels
      run: python3 -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_SKIP: "*musllinux* pp* *-manylinux_i686"
        CIBW_BUILD_VERBOSITY: 1

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-linux
        path: ./wheelhouse/*.whl

  build_macos:
    name: Macos Wheels
    runs-on: macos-14
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install cibuildwheel
      run: python3 -m pip install cibuildwheel==3.4.1

    - name: Build wheels
      run: python3 -m cibuildwheel --output-dir wheelhouse
      env:
        # Apple M1 and Intel
        CIBW_ARCHS_MACOS: arm64
        CIBW_SKIP: "pp*"
        CIBW_BUILD_VERBOSITY: 1

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-macos
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build Source Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  upload_pypi:
    name: Upload to PyPI
    needs: [build_linux, build_macos, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/multi-agent-ale-py
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*"
          merge-multiple: true
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
